spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:file:./target/h2db/db/demo;DB_CLOSE_DELAY=-1
    username: demo
    password:
    h2:
      console:
        enabled: false
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      database: H2
      show-sql: true
      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.connection.provider_disables_autocommit: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
    liquibase:
      contexts: dev

nemesis:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 (you can type `echo 'secret-key'|base64` on your command line)
        base64-secret: Nzg1NWRlZTA3NjdlOWMyOTk5MTQ3M2Q2MjExZjVmMzk1NzE2ZjhhNjNjMTU4NTRiYWMxN2EyOWM4ZTdjOGUxYTM5ODk5NjkwZDIwNDFlODdlMTcyYWNjMjFkZWQ1M2Q1ZDE4N2FiZDExM2I2NTA5ZTMzMWI3OTU3NTc5Y2UwMzc=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
